#!/usr/bin/env bash

# Copyright 2016 The Kubernetes Authors All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The install script is based off of the MIT-licensed script from glide,
# the package manager for Go: https://github.com/Masterminds/glide.sh/blob/master/get

PROJECT_NAME="hydra"

: ${HYDRA_INSTALL_DIR:="/usr/local/bin"}

# initArch discovers the architecture for this system.
initArch() {
  ARCH=$(uname -m)
  case $ARCH in
    armv5*) ARCH="armv5";;
    armv6*) ARCH="armv6";;
    armv7*) ARCH="armv7";;
    aarch64) ARCH="arm64";;
    x86) ARCH="386";;
    x86_64) ARCH="amd64";;
    i686) ARCH="386";;
    i386) ARCH="386";;
  esac
}

# initOS discovers the operating system for this system.
initOS() {
  OS=$(echo `uname`|tr '[:upper:]' '[:lower:]')

  case "$OS" in
    # Minimalist GNU for Windows
    mingw*) OS='windows';;
  esac
}

# runs the given command as root (detects if we are root already)
runAsRoot() {
  local CMD="$*"
  
  if [ $EUID -ne 0 ]; then
    CMD="sudo $CMD"
  fi
  
  $CMD
}

# verifySupported checks that the os/arch combination is supported for
# binary builds.
verifySupported() {
  local supported="linux-amd64\ndarwin-amd64\nlinux-386"
  if ! echo "${supported}" | grep -q "${OS}-${ARCH}"; then
    echo "No prebuild binary for ${OS}-${ARCH}."
    echo "To build from source, go to https://github.com/benkeil/hydra"
    exit 1
  fi

  if ! type "curl" > /dev/null && ! type "wget" > /dev/null; then
    echo "Either curl or wget is required"
    exit 1
  fi
}

# checkDesiredVersion checks if the desired version is available.
checkDesiredVersion() {
  # Use the GitHub releases webpage for the project to find the desired version for this project.
  local release_url="https://api.github.com/repos/benkeil/hydra/releases/${DESIRED_VERSION:-latest}"
  if type "curl" > /dev/null; then
    TAG=$(curl -SsL $release_url | grep tag_name | cut -d '"' -f 4)
  elif type "wget" > /dev/null; then
    TAG=$(wget -q -O - $release_url | grep tag_name | cut -d '"' -f 4)
  fi
  if [ "x$TAG" == "x" ]; then
    echo "Cannot determine ${DESIRED_VERSION} tag."
    exit 1
  fi
}

# checkHydraInstalledVersion checks which version of helm is installed and
# if it needs to be changed.
checkHydraInstalledVersion() {
  if [[ -f "${HYDRA_INSTALL_DIR}/${PROJECT_NAME}" ]]; then
    local version=$(hydra --version | cut -d' ' -f3)
    if [[ "$version" == "$TAG" ]]; then
      echo "Hydra ${version} is already ${DESIRED_VERSION:-latest}"
      return 0
    else
      echo "Hydra ${TAG} is available. Changing from version ${version}."
      return 1
    fi
  else
    return 1
  fi
}

# downloadFile downloads the latest binary package and also the checksum
# for that binary.
downloadFile() {
  HYDRA_DIST="hydra-$OS-$ARCH.tar.gz"
  DOWNLOAD_URL="https://github.com/benkeil/hydra/releases/download/$TAG/$HYDRA_DIST"
  CHECKSUM_URL="https://s3.eu-central-1.amazonaws.com/benkeil-hydra/${TAG}/${HYDRA_DIST}.sha265"
  HYDRA_TMP_FILE="/tmp/$HYDRA_DIST"
  HYDRA_SUM_FILE="/tmp/$HYDRA_DIST.sha256"
  
  echo "Downloading $CHECKSUM_URL"
  if type "curl" > /dev/null; then
    curl -SsL "$CHECKSUM_URL" -o "$HYDRA_SUM_FILE"
  elif type "wget" > /dev/null; then
    wget -q -O "$HYDRA_SUM_FILE" "$CHECKSUM_URL"
  fi
  
  echo "Downloading $DOWNLOAD_URL"
  if type "curl" > /dev/null; then
    curl -SsL "$DOWNLOAD_URL" -o "$HYDRA_TMP_FILE"
  elif type "wget" > /dev/null; then
    wget -q -O "$HYDRA_TMP_FILE" "$DOWNLOAD_URL"
  fi
}

# installFile verifies the SHA256 for the file, then unpacks and
# installs it.
installFile() {
  HYDRA_TMP="/tmp/$PROJECT_NAME"
  local sum=$(openssl sha1 -sha256 ${HYDRA_TMP_FILE} | awk '{print $2}')
  local expected_sum=$(cat ${HYDRA_SUM_FILE})
  if [ "$sum" != "$expected_sum" ]; then
    echo "SHA sum of $HYDRA_TMP does not match. Aborting."
    exit 1
  fi

  HYDRA_FILE="hydra-$OS-$ARCH"
  mkdir -p "$HYDRA_TMP"
  tar xf "$HYDRA_TMP_FILE" -C "$HYDRA_TMP"
  HYDRA_TMP_BIN="$HYDRA_TMP/$HYDRA_FILE"
  echo "Preparing to install into ${HYDRA_INSTALL_DIR}"
  runAsRoot cp "$HYDRA_TMP_BIN" "$HYDRA_INSTALL_DIR/$PROJECT_NAME"
}

# fail_trap is executed if an error occurs.
fail_trap() {
  result=$?
  if [ "$result" != "0" ]; then
    if [[ -n "$INPUT_ARGUMENTS" ]]; then
      echo "Failed to install $PROJECT_NAME with the arguments provided: $INPUT_ARGUMENTS"
      help
    else
      echo "Failed to install $PROJECT_NAME"
    fi
    echo -e "\tFor support, go to https://github.com/benkeil/hydra."
  fi
  exit $result
}

# testVersion tests the installed client to make sure it is working.
testVersion() {
  set +e
  echo "$PROJECT_NAME installed into $HYDRA_INSTALL_DIR/$PROJECT_NAME"
  HYDRA="$(which $PROJECT_NAME)"
  if [ "$?" = "1" ]; then
    echo "$PROJECT_NAME not found. Is $HYDRA_INSTALL_DIR on your "'$PATH?'
    exit 1
  fi
  set -e
}

# help provides possible cli installation arguments
help () {
  echo "Accepted cli arguments are:"
  echo -e "\t[--help|-h ] ->> prints this help"
  echo -e "\t[--version|-v <desired_version>] . When not defined it defaults to latest"
  echo -e "\te.g. --version v2.4.0  or -v latest"
}

# Execution

#Stop execution on any error
trap "fail_trap" EXIT
set -e

# Parsing input arguments (if any)
export INPUT_ARGUMENTS="${@}"
set -u
while [[ $# -gt 0 ]]; do
  case $1 in
    '--version'|-v)
       shift
       if [[ $# -ne 0 ]]; then
           export DESIRED_VERSION="${1}"
       else
           echo -e "Please provide the desired version. e.g. --version v2.4.0 or -v latest"
           exit 0
       fi
       ;;
    '--help'|-h) 
       help
       exit 0
       ;;
    *) exit 1
       ;;
  esac
  shift
done
set +u

initArch
initOS
verifySupported
checkDesiredVersion
if ! checkHydraInstalledVersion; then
  downloadFile
  installFile
fi
testVersion